# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/P3_urbana_S2026.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_2/design_1_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] -quiet

# Block Designs: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/bd_892d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_0/bd_892d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_2/bd_892d_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_3/bd_892d_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_4/bd_892d_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_12/bd_892d_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_13/bd_892d_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_14/bd_892d_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_15/bd_892d_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_16/bd_892d_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_17/bd_892d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_18/bd_892d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_19/bd_892d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_20/bd_892d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_21/bd_892d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_22/bd_892d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_23/bd_892d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_24/bd_892d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_25/bd_892d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_26/bd_892d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_27/bd_892d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_28/bd_892d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_29/bd_892d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_30/bd_892d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_31/bd_892d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_32/bd_892d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_neorv32_vivado_ip_0_3/design_1_neorv32_vivado_ip_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_neorv32_vivado_ip_0_3 || ORIG_REF_NAME==design_1_neorv32_vivado_ip_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pong_axi_0_1/design_1_pong_axi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pong_axi_0_1 || ORIG_REF_NAME==design_1_pong_axi_0_1} -quiet] -quiet

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_1/bd_892d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_2/bd_892d_arinsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_3/bd_892d_rinsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_4/bd_892d_awinsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_5/bd_892d_winsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_6/bd_892d_binsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_7/bd_892d_aroutsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_8/bd_892d_routsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_9/bd_892d_awoutsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_10/bd_892d_woutsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_11/bd_892d_boutsw_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_12/bd_892d_arni_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_13/bd_892d_rni_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_14/bd_892d_awni_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_15/bd_892d_wni_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_16/bd_892d_bni_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_20/bd_892d_s00a2s_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_21/bd_892d_sarn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_22/bd_892d_srn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_23/bd_892d_sawn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_24/bd_892d_swn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_25/bd_892d_sbn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_26/bd_892d_m00s2a_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_27/bd_892d_m00arn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_28/bd_892d_m00rn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_29/bd_892d_m00awn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_30/bd_892d_m00wn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/bd_0/ip/ip_31/bd_892d_m00bn_0_ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/ooc.xdc

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/ip/design_1_smartconnect_0_2/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_2 || ORIG_REF_NAME==design_1_smartconnect_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/denny/final/final.gen/sources_1/bd/design_1/design_1_ooc.xdc
